name: Python application

on:
  pull_request:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Test with pytest
        run:  python3 test_file.py

  notify:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.example.com
          server_port: 587
          username: ${{ secrets.i201877@nu.edu.pk }}
          password: ${{ secrets.f@st2011351 }}
          subject: "Test Results: ${{ job.status }}"
          to: i200471@nu.edu.pk
          from: i201877@nu.edu.pk
          body: |
            The test results for the latest commit are: ${{ job.status }}
